name: Update README with Latest Announcement

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes.

permissions:
  contents: write
      

jobs:
  update-readme:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch the latest announcement from Discussions
        id: get-announcement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $query = 'query { repository(owner: "microsoft", name: "EnterpriseScale-IAC-and-CICD") { discussions(first: 1, orderBy: {field: CREATED_AT, direction: DESC}) { nodes { title url } } } }'
          $response = Invoke-RestMethod -Uri 'https://api.github.com/graphql' -Method POST -Headers @{Authorization = "bearer $env:GITHUB_TOKEN"} -ContentType "application/json" -Body (ConvertTo-Json -Compress -InputObject @{query = $query})
          $latestAnnouncement = $response.data.repository.discussions.nodes[0]
          $announcementText = $latestAnnouncement.title + " - " + $latestAnnouncement.url
          echo "announcement=$latestAnnouncement" >> $env:GITHUB_OUTPUT

      - name: Update README
        shell: pwsh
        run: |
          echo "Announcement: ${{ steps.get-announcement.outputs.announcement }}"
          $announcement = "${{ steps.get-announcement.outputs.announcement }}"
          $content = Get-Content README.md
          $newContent = $content -replace "(?s)(<!-- announcement-start -->).*?(<!-- announcement-end -->)", "`$1`n## Latest Announcement`n$announcement`n`$2"
          $newContent | Set-Content README.md
          git config --local user.email "paullizer@microsoft.com"
          git config --local user.name "Paul Lizer"
          git add README.md
          git commit -m "Update README with the latest announcement"
          git push
