name: Update README with Latest Announcement

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes.

permissions: write-all

jobs:
  update-readme:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch the latest announcement from Discussions
        id: get-announcement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $headers = @{
            "Authorization" = "token $env:GITHUB_TOKEN"
          }
          $uri = "https://api.github.com/repos/${{ github.repository }}/discussions?per_page=1"
          $response = Invoke-RestMethod -Uri $uri -Headers $headers
          $latestAnnouncement = "${response[0].title} - ${response[0].html_url}"
          echo "announcement=$latestAnnouncement" >> $env:GITHUB_OUTPUT

      - name: Update README
        shell: pwsh
        run: |
          $announcement = "${{ steps.get-announcement.outputs.announcement }}"
          $content = Get-Content README.md
          $newContent = $content -replace "(?s)(<!-- announcement-start -->).*?(<!-- announcement-end -->)", "`$1`n## Latest Announcement`n$announcement`n`$2"
          $newContent | Set-Content README.md
          git add README.md
          git commit -m "Update README with the latest announcement"
          git push