name: Update README with Latest Announcement

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

permissions:
  contents: write
      
jobs:
  update-readme:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch the latest announcement from Discussions
        id: get-announcement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $query = 'query { repository(owner: "microsoft", name: "EnterpriseScale-IAC-and-CICD") { discussions(first: 1, orderBy: {field: CREATED_AT, direction: DESC}) { nodes { title url } } } }'
          $response = Invoke-RestMethod -Uri 'https://api.github.com/graphql' -Method POST -Headers @{Authorization = "bearer $env:GITHUB_TOKEN"}  -ContentType "application/json" -Body (ConvertTo-Json -Compress -InputObject @{query = $query})
          $latestAnnouncement = $response.data.repository.discussions.nodes[0]
          $titleText = $latestAnnouncement.title
          $urlText = $latestAnnouncement.url
          echo "title=$titleText" >> $env:GITHUB_OUTPUT
          echo "url=$urlText" >> $env:GITHUB_OUTPUT

      - name: Update README
        shell: pwsh
        run: |
          echo "Announcement: ${{ steps.get-announcement.outputs.title }} - ${{ steps.get-announcement.outputs.url }}"
          $title = "${{ steps.get-announcement.outputs.title }}"
          $url = "${{ steps.get-announcement.outputs.url }}"
          $content = Get-Content README.md
          $newContent = $content -replace "(?s)<!-- announcement-start -->.*?<!-- announcement-end -->", "<!-- announcement-start -->`n> [!IMPORTANT]`n>`n> **Latest Announcement:** [$title](#$url)`n`n<!-- announcement-end -->"
          $newContent | Set-Content README.md
          git config --local user.email "paullizer@microsoft.com"
          git config --local user.name "Paul Lizer"
          git add README.md
          git commit -m "Update README with the latest announcement"
          git push
