name: Update README with Latest Announcement

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour; adjust as needed.

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch the latest announcement from Discussions
        id: get-announcement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_ANNOUNCEMENT=$(curl -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/discussions?per_page=1" \
          | jq -r '.[0] | "\(.title) - \(.html_url)"') # Update API URL as needed
          echo "::set-output name=announcement::${LATEST_ANNOUNCEMENT}"

      - name: Update README
        run: |
          ANNOUNCEMENT="${{ steps.get-announcement.outputs.announcement }}"
          sed -i "/<!-- announcement-start -->/,/<!-- announcement-end -->/c\<!-- announcement-start -->\n## Latest Announcement\n${ANNOUNCEMENT}\n<!-- announcement-end -->" README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update README with the latest announcement"
          git push